### ISSUE TITLE
ENOENT: no such file or directory, open './phantom/index.pack.js'

### ISSUE THREAD

**Issue by n-kort** [cytoscape/cytosnap#13]
Hey, getting this error as soon as I run `snap.shot()`. Any ideas?

**Comment by maxkfranz** [comment]
Maybe the ref in the index.html is wrong?  Does it work if you change the ref from index.pack.js to index.js?  (I can't try this out until 28 Oct as I'm away)

**Comment by n-kort** [comment]
Gave that a try already.. seems to be [index.js#L42](https://github.com/cytoscape/cytosnap/blob/master/index.js#L42) in particular though.

**Comment by n-kort** [comment]
Hmm, using `path.join(__dirname, '/phantom/index.pack.js')` fixes this particular error, but then I just get `info: ReferenceError: Can't find variable: cy` instead. Not really sure where that's even being thrown though.

**Comment by maxkfranz** [comment]
Pushed a change that looks like it fixes it (published as 1.1.1).  Let me know if it works for you

**Comment by n-kort** [comment]
Great, that does seem to have done it!
