### ISSUE TITLE
`cose` layout doesn't work

### ISSUE THREAD

**Issue by n-kort** [cytoscape/cytosnap#15]
The graph does not render properly when using the `cose` layout:

![cose](https://cloud.githubusercontent.com/assets/1377218/24967916/e08bffda-1fab-11e7-83a3-02e77af188e2.png)

This image was generated by the test runner, the nodes are all grouped at 0x0.

Any tips on getting this to work?

**Comment by maxkfranz** [comment]
Have you specified initial positions or used `randomize: true`?  Force-directed layouts tend not to work with all nodes starting at (0, 0).

**Comment by n-kort** [comment]
The randomise option is set, but the results are the same either way. Don't think it's possible to set initial positions in our case.

**Comment by maxkfranz** [comment]
Cose works on Node, but it looks like it doesn't work on Phantom.  Maybe webworker support is bad in Phantom.  It might be better with 3.0

**Comment by maxkfranz** [comment]
https://github.com/cytoscape/cytosnap/issues/16

**Comment by maxkfranz** [comment]
For now, you could run CoSE on a headless instance of Cytoscape (on Node) and then just pass in `cy.elements().jsons()` to Cytosnap with the preset layout.

**Comment by n-kort** [comment]
Thanks @maxkfranz, that seems to work a lot better. Oddly I couldn't get the nodes to actually stay within the bounds I'd set... Have witched to the spread layout instead.
