### ISSUE TITLE
Update for cytoscape@3.0.0

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytosnap#16]

**Comment by d2fong** [comment]
@maxkfranz what needs to be done to update cytosnap to use cy.js 3?

**Comment by maxkfranz** [comment]
I'm not sure if it's using any 2.x-only APIs.  `package.json` needs to be updated and it needs to be tested.

**Comment by maxkfranz** [comment]
Released as 2.0

**Comment by maxkfranz** [comment]
No support for cytoscape@2, though.  It would complicate testing etc., and all new projects should be using cytoscape@3 anyway.
