### ISSUE TITLE
Fatal Windows exception code 0xc0000005 PhantomJS has crashed

### ISSUE THREAD

**Issue by rura6502** [cytoscape/cytosnap#17]
i tried to drawing data 93,240 nodes, 50,000 edges. but i met this

error: Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

i think this is memory issues. i am trying is it possible to drawing graph with a lot of data fastly.

when i try using cytoscapejs in only client, i can get graph with little long time. but in cytosnap is fail.

is there any segestion?

**Comment by 130nk3r5** [comment]
Was this issue resolved. Because I still get it!

**Comment by maxkfranz** [comment]
Either the graph is too big for your machine with PhantomJS or the image is too large.

**Comment by maxkfranz** [comment]
Phantom issues won't apply to the package anymore with the change to Puppeteer.
