### ISSUE TITLE
Switch to Puppeteer

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytosnap#18]
https://github.com/GoogleChrome/puppeteer

This would be a better long-term solution than PhantomJS, and it may be lighter on system resources.

**Comment by d2fong** [comment]
ubuntu steps for phantomjs:
https://gist.github.com/d2fong/8b7b48dd2c853034e5785bedf992e6aa

ubuntu steps for puppeteer:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker
