### ISSUE TITLE
Executable path option for Puppeteer

### ISSUE THREAD

**Issue by JanSvejda** [cytoscape/cytosnap#22]
https://github.com/cytoscape/cytosnap/blob/33e774fb800e3f2723398e50b355d9a59b756a2c/index.js#L102

Hi, we are using Cytosnap to create a dependency graph in our ChatBot, which we run in an Alpine Docker container. I am having issues with launching Chromium in the container. According to [Puppeteer troubleshooting docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md), the solution is there, but we just need to pass the "executablePath" parameter to Puppeteer.

Would it be possible to add that as an option? If you would like, I can do it as well.

I am using Node 10.15.0 and Cytosnap 3.0.0.

**Comment by maxkfranz** [comment]
Would you be open to making a PR to expose a `puppeteer` field within the `options` object for `cytosnap()`?  That way, you could customise any of the `puppeteer.launch()` options as you like.

**Comment by JanSvejda** [comment]
Sure, will do. I read the contribution guidelines, but is there anything else specific I should keep in mind?

**Comment by maxkfranz** [comment]
As long as the code works well and is easily readable, feel free to do whatever you think makes sense.

**Comment by JanSvejda** [comment]
I have found out that there exists an environment variable which Puppeteer looks up before launch (PUPPETEER_EXECUTABLE_PATH) so I have solved the problem with that.

I have done the small change to the start function anyway. Would you like the pull request for it?

**Comment by maxkfranz** [comment]
Yes, that would be great.  Puppeteer might not always expose important options as env vars, and I'd like to be able to support as many host systems as possible.
