### ISSUE TITLE
How to use in a thread-safe manner?

### ISSUE THREAD

**Issue by jeshan** [cytoscape/cytosnap#24]
From the quick start, we can see that the `start` function is called then a `shot` is taken.
If invoked this way, isn't there a performance penalty?

Otherwise I'm considering calling `start` and reuse the object returned. In this case, can we then call `shot` multiple times in a thread safe manner?

**Comment by maxkfranz** [comment]
Each `snap` instance must have only one `shot()` call running at once.  If you want to run more than one at once, you should use a pool of `snap` objects.

**Comment by maxkfranz** [comment]
Actually that restriction may not apply anymore.  Each call to `shot()` should be independent, so you can just use a single `snap`.
