### ISSUE TITLE
Stylesheet in function format

### ISSUE THREAD

**Issue by hasanbalci** [cytoscape/cytosnap#26]
I'm trying to render an SBGN map on the server side, but I have a problem with the style option. When I provide a stylesheet to cytosnap  in JSON format as follows:
```
elements: cy.json().elements,
style: [
    {
      selector: 'node',
      style: {
        'background-color': 'red'
      }
    }
 ]
```
This works fine and applies the given style. However, if I provide a stylesheet in function format, it doesn't apply stylesheet and returns an image with default cytoscape.js style. Since I'm trying to render an SBGN map, I used the stylesheet from cytoscape-sbgn-stylesheet as follows:
```
const cytoscape = require('cytoscape');
const sbgnStylesheet = require('cytoscape-sbgn-stylesheet');
const convertSBGNtoCytoscape = require('sbgnml-to-cytoscape');

let cyData = convertSBGNtoCytoscape(sbgnData);
cy.add(data);
....

snap.start().then(function(){
  return snap.shot({
    elements: cy.json().elements,
    style: sbgnStylesheet(cytoscape),
   ....
```
but this didn't work. There are two explanations in README about style option:
- `style: undefined, // a cytoscape.js stylesheet in json format (or a function that returns it)`
- `// (specifying style or layout via a function is useful in cases where you can't send properly serialisable json)`
From these explanations, I supposed it also accepts stylesheets in function format. 

Am I missing some point here or doesn't cytosnap support function format? If it doesn't support, I may try to add it because I think there is no other way to apply sbgn-stylesheet.

Thanks!

**Comment by maxkfranz** [comment]
With Puppeteer, everything Cytoscape-related must run within Puppeteer's browser instance.  This means you don't have access to anything in Node.  This is, for example, why you have to declare imported layouts explicitly: https://github.com/cytoscape/cytosnap#cytosnapuse

If you use a function, it's just a pure function that runs in the browser instance, e.g.

```
style: function(){ /* build up a style and return it */ }
```

So if you have dependencies, those need to be injected into the browser instance as globals if you want to access them in that function.  I don't think there's currently any functionality for that outside of layouts.

**Comment by hasanbalci** [comment]
@maxkfranz Thanks for the answer, I didn't know that. Then I need to imitate the usage of layouts to be able to inject stylesheet. I'll give it a try.

**Comment by hasanbalci** [comment]
@maxkfranz I managed to do it. I'm considering to make a PR, when I tidy up my own project, for the injection of dependencies other than layouts (I think this may only be needed to provide different stylesheets such as cytoscape-sbgn-stylesheet). Thanks again!

**Comment by maxkfranz** [comment]
Sounds good.  Feel free to post updates here as you discover new things about the use case.  When you get it to the point that a PR would make sense, that would be great!
