### ISSUE TITLE
cytosnap issue with vite.js

### ISSUE THREAD

**Issue by JulienTom33** [cytoscape/cytosnap#27]
Hi, 

I want to use cytosnap in my vite.js project.
But when i import the package, i have this error: "Uncaught (in promise) ReferenceError: require is not defined"

`var cytosnap  = require('cytosnap');
var snap = cytosnap();`

Is there any issue?

Thanks!

**Comment by maxkfranz** [comment]
Cytosnap is for the server, not the client.

See:

- https://github.com/cytoscape/cytosnap#cytosnap
- https://pptr.dev

**Comment by JulienTom33** [comment]
Okay! 

So i can use it in an express.js server?
